config/routes.rb
Rails.application.routes.draw do
	get 'download' => 'users#download_lectures'
	get 'check-details' => 'users#check_details'
	get 'download-icard' => 'users#id_card'
	post 'login' => 'sessions#create'
	get 'logout' => 'sessions#destroy'
  post 'create' => 'users#create'
	post 'mentorship-registration' => 'users#mentee_entry'
	get 'my-profile' => 'users#profile'
  post 'edit-profile' => 'users#edit_profile'
	
  get 'index' => 'static_pages#index'
  get 'activities' => 'static_pages#activities'
  get 'events' => 'static_pages#events'
  get 'involvements' => 'static_pages#involvements'
  get 'mentorship' => 'static_pages#mentorship'	
  get 'gallery' => 'static_pages#gallery'
  get 'contact-us' => 'static_pages#contact_us'


  root 'static_pages#index'








end

app/models/mentee.rb
class Mentee < ActiveRecord::Base	
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 200}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
	
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			redirect_to "/my-profile"
		else
			redirect_to "/?login=failed"
		end
	end
	
	def destroy
		log_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
		@user = User.new #as signup can be done on any page so @user must be defined in every controller
  end

  def activities
		@user = User.new
  end

  def events
		@user = User.new
  end

  def involvements
		@user = User.new
  end

  def mentorship
		@user = User.new
  end

   def gallery
    @user = User.new
  end
	
	def contact_us
		@user = User.new
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate, :except => [:create, :mentee_entry]
	def authenticate
		redirect_to("/?login=false") if current_user.nil?
	end
	
  def profile
		@user = User.new
		@mentee = Mentee.new
		if is_mentee? && current_mentee.image
			@profile_pic = "v2/#{current_mentee.image}"
		else 
			@profile_pic = "default_zigoby.png"
		end
  end

  def edit_profile
		if is_mentee?			
			@mentee = Mentee.update(current_mentee.id, mentee_params)
		else
			@mentee = Mentee.new(mentee_params)
			@mentee.user_id = current_user.id
		end
		if params[:mentee][:image]
			 uploaded_io = params[:mentee][:image]
			 file_ext = File.extname(uploaded_io.original_filename)
			 @mentee.image = "image_#{current_user.id}#{file_ext}" #uploaded_io.original_filename
			 File.open(Rails.root.join('app/assets/images', 'uploads', @mentee.image), 'wb') do |file|
				 file.write(uploaded_io.read)
			 end
			 Cloudinary::Uploader.upload(File.open(Rails.root.join('app/assets/images', 'uploads', @mentee.image)), :public_id => "image_#{current_user.id}")
		end
		# if params[:image].present?
			# preloaded = Cloudinary::PreloadedFile.new(params[:image])         
			# raise "Invalid upload signature" if !preloaded.valid?
			# @mentee.image = preloaded.identifier
		# end
		if @mentee.save
			redirect_to "/my-profile/?saved=true"
		else 
			redirect_to(:back)
		end
  end
	
	def create
		@user = User.new(user_params)
		flash[:success] = "Fill out the other details to download ICARD"
		flash[:danger] = "Please provide the valid details."
		if @user.save
			log_in @user
			redirect_to "/my-profile"
		else
			redirect_to "/?signup=failed"
		end
	end
	
	def mentee_entry
		@user = User.new(user_params)
		@mentee = Mentee.new
		if @user.save
			@mentee.user_id = @user.id
			if @mentee.save
				log_in @user
				redirect_to "/my-profile"
			end			
		else
			redirect_to "/mentorship/?registration=failed"
		end
	end
	
	def id_card
		#@user = User.new
		if !all_details_filled?
			redirect_to "/my-profile?details_check=failed" and return
		end		
		respond_to do |format|
      format.html
			format.pdf do
        render pdf: "robotic-mentorship-id-card-2015-16"   # Excluding ".pdf" extension.
      end
    end
  end
	
	def download_lectures
		if params[:lecture].in?(['Lecture1.pdf', 'Lecture2.pdf', 'Lecture3.pdf','Lecture4.pdf','Lecture5.pdf',
			'Lecture6.pdf','Lecture7.pdf']) 
			redirect_to "/data/"+params[:lecture] 
		else 
			redirect_to "/activities?conducted=false"
		end
	end
	
	private
	
	def all_details_filled?
		current_mentee.contact_no && current_mentee.enrollment_no && current_mentee.branch && current_mentee.receipt_no && current_mentee.sex && current_mentee.image ? true : false
	end
	
	def user_params
		params.require(:user).permit(:name, :email, :password)
	end
	
	def mentee_params
		params.require(:mentee).permit(:contact_no, :enrollment_no, :branch, :sex, :receipt_no, :verified)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
		session[:user_id] = user.id
	end
	
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	
	def logged_in?
		!current_user.nil?
	end
	
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
	
	def current_mentee
		@current_mentee ||= Mentee.find_by(user_id: current_user.id)
	end
	
	def is_mentee?
		!current_mentee.nil?
	end
	
	def all_details_filled?
		if current_mentee.contact_no && current_mentee.enrollment_no && current_mentee.branch && current_mentee.receipt_no && current_mentee.sex ? true : false
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="copyright sep-top-xs sep-bottom-xs">
	<div class="container">
		<div class="row">
			<div class="col-md-8" style="margin-top: 1%;">
			<small>
			<a href="/contact-us">CONTACT ZONAL REPREZENTATIVE</a> | 
			<a href="/#about_us">ABOUT</a> | 
			<a href="/contact-us">TEAM</a> | 
			<a href="https://www.asme.org">ASME.ORG</a> |
			<a href="https://www.facebook.com/pages/ASME-IIT-Roorkee-Chapter/107997429253513" target="_blank">
			<img src="/assets/fb_logo.png"  width="5%" height="5%">FACEBOOK</a> | 
			<a href="https://www.linkedin.com/groups/3815637" target="_blank">
			<img src="/assets/linkedIn_logo.png"  width="3%" height="3%"> LINKEDIN</a>
			</small>
			</div>
			<div class="col-md-4 mobhide" style="margin-top: 1%;"><small style="float:right;">ALL RIGHTS RESERVED.</small></div>
		</div>
	</div>
</div>
</div>

<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title signup_title" id="myModalLabel">SIGN UP</h4>
      </div>
			<div id="signup_message"></div>
      <div class="modal-body">
        <%= form_for @user, :url => "/create", :html => {:class => "form-horizontal"} do |f| %>
					<div class="form-group">
						<%= f.label :name, class: "col-md-4 control-label" %>
						<div class="col-md-6">
							<%= f.text_field :name, class: "form-control", placeholder: "Name" %>
						</div>
					</div>
					<div class="form-group">
						<%= f.label :email, class: "col-md-4 control-label" %>
						<div class="col-md-6">
							<%= f.email_field :email, class: "form-control", placeholder: "someone@anything.com" %>
						</div>
					</div>
					<div class="form-group">
						<%= f.label :password, class: "col-md-4 control-label" %>
						<div class="col-md-6">
							<%= f.password_field :password, class: "form-control", placeholder: "Atleast 6 character" %>
						</div>
					</div>
					<%= f.submit "Sign Up", class: "btn btn-primary col-md-offset-5" %>
				<% end %>
			</div>
    </div>
  </div>
</div>

app/views/layouts/_static_pages.html.erb
    <style>#qLtempOverlay{display:none;}</style>
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700%7COpen+Sans:300italic,400italic,600italic,700italic,800italic,300,400,600,700">
    <style id="fit-vids-style">.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}</style>
    <!--[if lt IE 9]>
    <p class="browsehappy">You are using an strong outdated browser. <br>Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
<div class="page">
<!-- Start Nav Section-->

<nav id="main-navigation" role="navigation" class="navbar navbar-fixed-top navbar-standard">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle"><span class="glyphicon glyphicon-align-justify"></span></button><a href="/" class="navbar-brand"><img src="/assets/logo.jpg" alt="" class="logo-white"><img src="/assets/logo.jpg" alt="" class="logo-dark"></a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right service-nav">
				<li>
					<a id="dropdownMenuLogin" href="#" data-toggle="dropdown" class="upper dropdown-toggle">
						<% if logged_in? %><%= current_user.name %><span class="caret"></span>
						<% else %> Login
						<% end %>
					</a>
					<div aria-labelledby="dropdownMenuLogin" class="dropdown-menu widget-box">
						<% if logged_in? %>
							<ul>
								<li>
									<% if is_mentee? %>
										<%= link_to "My Profile", "/my-profile" %>
									<% else %>
										<%= link_to "Mentorship Registration", "/my-profile" %>
									<% end %>
								</li>
								<li><%= link_to "Logout", "/logout" %></li>
							</ul>
						<% else %>
							<%= form_for(:session, url: "/login") do |f| %>								
								<div class="form-group">									
									<label class="sr-only">Email</label>
									<%= f.email_field :email, class: "form-control input-lg", placeholder: "Email" %>
								</div>
								<div class="form-group">
									<label class="sr-only">Password</label>
									<%= f.password_field :password, class: "form-control input-lg", placeholder: "Password" %>
								</div>
								<div class="form-inline form-group">
									<%= f.submit "Login", class: "btn btn-primary btn-xs" %>
									<!-- <div class="checkbox" style="float: right;">
										<label>
											<%= f.check_box :remember_me %> Remember me
										</label>
									</div> -->
								</div><a href="#"><small>Lost your Password?</small></a><span id="signup_link" data-toggle="modal" data-target="#signUpModal">SignUp</span>
							<% end %>
						<% end %>							
					</div>
				</li>              
			</ul>
			<button type="button" class="navbar-toggle"><span class="glyphicon glyphicon-remove"></span></button>
			<ul class="nav yamm navbar-nav navbar-left main-nav">
				<li class="dropdown"><a href="<%= activities_path %>" title="Activities" data-toggle="dropdown" data-hover="dropdown" id="menu_item_activities" data-ref="/activities" class="dropdown-toggle">Activities<span class="caret"></span></a>
					<ul aria-labelledby="menu_item_activities" class="dropdown-menu">
									<li><a href="<%= activities_path %>#lectures" title="Lectures" data-ref="home-3">Lectures</a></li>
									<li><a href="<%= activities_path %>#workshops" title="workshops" data-ref="home-3">Workshops</a></li>
					</ul>
				</li>
				<!-- istanzio un id univoco-->
				<li class="dropdown"><a href="events" title="Events" data-toggle="dropdown" data-hover="dropdown" id="menu_item_events" data-ref="#" class="dropdown-toggle">Events<span class="caret"></span></a>
					<ul aria-labelledby="menu_item_events" class="dropdown-menu">
					 <li><a href="/involvements">Involvements</a></li>
					 <li><a href="/events">Events Organised</a></li>
					</ul>
				</li>
				<!-- istanzio un id univoco-->
				<li><a href="/#about_us" id="menu_item_about_us">About Us</a></li>
				<!-- istanzio un id univoco-->
				<li><a href="/mentorship" id="menu_item_discussion">Mentorship Programme</a></li>
				<!-- <li><a href="/gallery" id="menu_item_discussion">Gallery</a></li> -->
				<!-- <li><a href="/discussion" id="menu_item_discussion">Discussion</a></li> -->
				<li><a href="/contact-us" id="menu_item_contact_us">Contact Us</a></li>
			</ul>
		</div>
	</div>
</nav>
<%= render "shared/messages" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ASME IIT ROORKEE</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="Keywords" content="asme, mechanical, engineering, iit, roorkee, iit roorkee, asme iitr, iitr">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
  <link rel="icon" href="https://www.asme.org/favicon.ico" type="image/x-icon">
	<link rel="shortcut icon" href="https://www.asme.org/favicon.ico" type="image/x-icon">
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Montserrat:400,700%7COpen+Sans:300italic,400italic,600italic,700italic,800italic,300,400,600,700" hreflang="en">
</head>
<body>
<%= render 'layouts/static_pages' %>
<%= yield %>
<%= render 'layouts/footer' %>
<%= #debug(params) if Rails.env.development? 
	%>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
    <div class="alert alert-danger alert-dismissible">
			<%= pluralize(@user.errors.count, "Error") %>:
			<% @user.errors.full_messages.each do |msg| %><%= msg %>, <% end %>
		</div>
	</div>
<% end %>

app/views/shared/_messages.html.erb
<% if params[:login] == "false" %>
	<div class="alert alert-danger col-md-offset-4 col-md-4 alert_login" ><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> Please login to perform this action.</div>
	<script>$(document).ready(function(){
	$("#dropdownMenuLogin").click();
	});</script>
<% end %>
<% if params[:login] == "failed" %>
	<div class="alert alert-danger col-md-offset-4 col-md-4 alert_login"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> Incorrect Email/Password combination.</div>
	<script>$(document).ready(function(){
	$("#dropdownMenuLogin").click();
	});</script>
<% end %>
<% if params[:signup] == "failed" %>
	<script>$(document).ready(function(){
	$("#signup_link").click();
	$("#signup_message").html('<div class="alert alert-danger">Please provide the valid details and make sure your password is atleast 6 character long.</div>');
	});</script>
<% end %>
<% if params[:details_check] == "failed" %>
	<script>$(document).ready(function(){
	$("#id_card_msg").html('<div class="alert alert-danger">Please provide all the details including a picture to downlaod the I-Card.</div>');
	});</script>
<% end %>
<% if params[:saved] == "true" %>
	<script>$(document).ready(function(){
	$("#id_card_msg").html('<div class="alert alert-success"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>Profile updated.</div>');
	});</script>
<% end %>
<% if params[:conducted] == "false" %>
	<script>$(document).ready(function(){
	$("#download_msg").html('<div class="alert alert-danger"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>This lecture has not been conducted yet.</div>');
	});</script>
<% end %>
<% if params[:registration] == "failed" %>
	<script>$(document).ready(function(){
	$("#registration_error").html('<div class="alert alert-danger">Please provide all the valid details and make sure your password is atleast 6 character long.</div>');
	});</script>
<% end %>

app/views/static_pages/activities.html.erb
<section class="parallax cover-div" style="background-image: url(/assets/lnw.jpg); background-size: 110%; background-position: 62.2364802933089% 21.11824%;">       
	<div class="  sep-top-2x sep-bottom-1x">
		<div class="container">
			<div class="text-center sep-bottom-md">
				<div class="section-title light">
					<h3 class="upper">On-Campus Activities</h3>
				</div>
			</div>			
		</div>
	</div>
</section>
<div id="lectures" class="link_div_lg"></div>
			
<section id="sellforcash" class="sep-top-2x sep-bottom-2x">
	<div class="container">
		<div class="row">
			<div class="col-md-5">
				<div class="section-title">
					<h2 class="bordered-left upper">Lectures</h2>
					<p class="lead" style="text-align:justify;">The section organizes a series of open lectures exclusively for the first year students (no registration required). The course content is mainly focused on providing a very strong foundation for the students with a perfect blend of theory and hands on experience. The students are taught the basics of Mechanism design, Drives and Electronics. All lectures are conducted by our team members only and once the lecture is conducted it will be available for download on login.</p>
				</div>
			</div>
			<div class="col-md-offset-1 col-md-6 lectures">
				<p id="download_msg"></p>
				<div data-wow-delay="1s" class="icon-box icon-lg icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<h5 class="lec1">Lecture 1: Introduction to Robotics</h5><!-- <span> Sep 7, 2016 | </span> --><span><a href="/download/?lecture=Lecture1.pdf" target="_blank">Download</a></span>
				</div>
				<div data-wow-delay="1s" class="icon-box icon-lg icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<h5>Lecture 2:  Mechanical Aspects of Robotics</h5><!-- <span> Sep 14, 2015 | </span> --><span><a href="/download/?lecture=Lecture2.pdf" target="_blank">Download</a></span>
				</div>
				<div data-wow-delay="1s" class="icon-box icon-lg icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<h5>Lecture 3: Sensors</h5><!-- <span> Sep 21, 2015 | </span> --><span><a href="/download/?lecture=Lecture3.pdf" target="_blank">Download</a></span>
				</div>
				<div data-wow-delay="1s" class="icon-box icon-lg icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<h5>Lecture 4: Inroduction to Microcontroller</h5><!-- <span> Sep 28, 2015 | </span> --><span><a href="/download/?lecture=Lecture4.pdf" target="_blank">Download</a></span>
				</div>
				<div data-wow-delay="1s" class="icon-box icon-lg icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<h5>Lecture 5: Inroduction to Arduino</h5><!-- <span> Oct 5, 2015 | </span> --><span><a href="/download/?lecture=Lecture5.pdf" target="_blank">Download</a></span>
				</div>
				<div data-wow-delay="1s" class="icon-box icon-lg icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<h5>Lecture 6: Arduino Programming</h5><!-- <span> Oct 12, 2015 | </span> --><span><a href="/download/?lecture=Lecture6.pdf" target="_blank">Download</a></span>
				</div>
				<div id="workshops"></div>
				<div data-wow-delay="1s" class="icon-box icon-lg icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<h5>Lecture 7: Line Following Bot</h5><!-- <span> Oct 19, 2015 | </span> --><span><a href="/download/?lecture=Lecture7.pdf" target="_blank">Download</a></span>
				</div>
			</div>	 
		</div>
	</div>
</section>

<!-- workshops -->
<section id="smartexchange" class="sep-bottom-2x">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<div class="section-title">
					<h2 class="bordered-left upper">Workshops</h2>
					<p class="lead" style="text-align:justify;">Just the lectures don’t help the cause of imparting technical knowledge to students therefore we carried out following workshops on different areas so that the students have the practical knowledge of the things they are learning. Each workshop continues the whole day (working hours) so students can manage there time accordingly. All workshops are taken by our team members only.</p>
				</div>
			</div>
			<div class="col-md-offset-1 col-md-7">
				<div data-wow-delay="1s" class="icon-box icon-lg sep-top-md icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<div class="icon-content img-circle"><span class="glyphicon glyphicon-tower"></span></i></div>
					<div class="icon-box-content">
						<h5>SolidWorks Workshop</h5>
						<p>Nearly all the features like sketch, boss and cut, fillets and chamfers, dimnsions, mating, etc are covered in this workshop which are required to be a Certified SOLIDWORKS Associate (CSWA).</p>
					</div>
				</div>
				<div data-wow-delay="1s" class="icon-box icon-lg sep-top-md icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<div class="icon-content img-circle"><span class="glyphicon glyphicon-resize-vertical"></span></div>
					<div class="icon-box-content">
						<h5>Line Following Robot Workshop</h5>
						<p>The line following workshop focused on complete fabrication of the bot along with connections and programming, wire connections and programming.</p>
					</div>
				</div>
				<div data-wow-delay="1s" class="icon-box icon-lg sep-top-md icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<div class="icon-content img-circle"><span class="glyphicon glyphicon-wrench"></span></div>
					<div class="icon-box-content">
						<h5>Workshop on Manual Robot</h5>
						<p>A workshop dedicated to the display and working of Manual robots where students get a chance to operate the bots.</p>
					</div>
				</div>
				<div data-wow-delay="1s" class="icon-box icon-lg sep-top-md icon-gradient " style="visibility: visible; -webkit-animation-delay: 1s;">
					<div class="icon-content img-circle"><span class="glyphicon glyphicon-volume-up"></span></div>
					<div class="icon-box-content">
						<h5>Workshop on Sensors and other components</h5>
						<p>This workshop aims to make the students aware of the different types of sensors like IR sensor, bump sensor, accelerometer, gyro meter, ultrasonic sensor etc, that are used by robots to accomplish various tasks.</p>
					</div>
				</div>
		 </div>
		</div>
	</div>
</section>

app/views/static_pages/contact_us.html.erb
<section class="parallax cover-div" style="background-image: url(/assets/contact3.jpg); background-size: 110%; background-position: 62.2364802933089% 28.11824%;">       
	<div class="  sep-top-2x sep-bottom-1x">
		<div class="container">
			<div class="text-center sep-bottom-md">
				<div class="section-title light">
					<h3 class="upper">Get in touch</h3>
				</div>
			</div>			
		</div>
	</div>
</section>
			
<section id="smartexchange" class="sep-top-2x sep-bottom-2x">
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<div class="section-title">
					<h5 class="bordered-left upper">Alumni</h5>
					<ul>
						<li>Jairaj Phase</li>
						<li>Dipak Shinde</li>
						<li>Nikhil Jain</li>
						<li>Nitish Garg</li>
						<li>Shashank Maurya</li>
						<li>Piyush Gupta</li>
						<li>Amol Shah</li>
						<li>Osin Tyagi</li>
					</ul>
				</div>
			</div>
			<div class="col-md-3">
				<div class="section-title">
					<h5 class="bordered-left upper">Fouth year</h5>
					<ul>
						<li>Vaibhav Goel<br />(Chairperson)</li>
						<li>Mrinaal Narang<br /> (Vice-Chairperson)</li>
						<li>Abishek GR<br />(Spokesperson)</li>
						<li>Aayush Sable<br />(Mentorship Manager)</li>
						<li>Abhishek Garg<br />(Technical Head)</li>
						<li>Nikhil Kr Soni<br/> (Treasurer) </li>
						
					</ul>
				</div>
			</div>
			<div class="col-md-3">
				<div class="section-title">
					<h5 class="bordered-left upper">Third year</h5>
					<ul>
						<li>Saumay Gupta <br/><b>(Secretary)</b><br /> +91-70 60 334154</li>
						<li>Sahil Jindal <br /> <b>(Joint Secretary)</b><br /> +91-87 91 700232</li>
						<li>Mukul Goyal <br /> <b>(Joint Secretary) </b></li>
						<li>Swabhiman Patnaik <br/> (Project Manager)</li>
						<li>Shobhit Mittal <br/> (Project Manager)</li>
						<li>Kshitij Tiwari <br /> (Event Manager) </li>
						<li>Mallikarjun Komma <br /> (Event Manager)</li>
						<li>Saumya Ranjan <br /> (Zonal Promotions Head)</li>
						<li>Sidharth Goel <br/> (Mentorship Incharge)</li>
						<li>Nikita Kusumakar <br/> (Mentorship Incharge)</li>
						<li>Aishwarya Mittal <br/> (Web Developer)</li>
					</ul>
				</div>
			</div>
			<div class="col-md-3">
				<div class="section-title">
					<h5 class="bordered-left upper">Second year</h5>
					<ul>
						<li>Rishabh Sharma</li>
						<li>Gaurav Singh Ranawat</li>
						<li>Ashutosh Dubey</li>
						<li>Utkarsh Verma</li>
						<li>Apoorv Valabh</li>
						<li>Prajjval Pundeer</li>
						<li>Prateek Chandra Pandey</li>
						<li>Abhishek jain</li>
						<li>Vibhu Baibhav</li>
						<li>Nikhil Arya</li>
						<li>Samarth Garg</li>
						<li>Dheeraj Buddhiraja</li>
						<li>Sunil Saini</li>
						<li>Nitin Kumar Mange</li>
						<li>Aditya Peshin</li>
						<li>Mansi Khare</li>
						<li>Apurva</li>
						
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/static_pages/gallery.html.erb
<section class="parallax cover-div" style="background-image: url(/assets/contact3.jpg); background-size: 110%; background-position: 62.2364802933089% 28.11824%;">       
	<div class="  sep-top-2x sep-bottom-1x">
		<div class="container">
			<div class="text-center sep-bottom-md">
				<div class="section-title light">
					<h3 class="upper">ASME IITR Gallery</h3>
				</div>
			</div>			
		</div>
	</div>
</section>
			
<section id="smartexchange" class="sep-top-2x sep-bottom-2x">
	
</section>

app/views/users/id_card.html.erb
this is the i card